#!/bin/bash

# generated by ai of course lol

# Directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONVERTER="$SCRIPT_DIR/base64_converter.py"
# The destination is one level up from the scripts directory
DEST_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

SOURCE_DIR="$1"

if [ -z "$SOURCE_DIR" ]; then
    echo "Usage: $0 <source_directory_with_pngs>"
    exit 1
fi

if [ ! -d "$SOURCE_DIR" ]; then
    echo "Error: Directory '$SOURCE_DIR' not found."
    exit 1
fi

echo "Converting PNGs from '$SOURCE_DIR' to base64 in '$DEST_DIR'..."

for png_file in "$SOURCE_DIR"/*.png; do
    # Handle case where no png files exist
    [ -e "$png_file" ] || continue

    filename=$(basename "$png_file")
    name="${filename%.*}"

    output_file="$DEST_DIR/${name}.b64"

    echo "Converting $filename -> ${name}.b64"
    python3 "$CONVERTER" "$png_file" > "$output_file"
done

echo "Batch conversion complete."
