#!/bin/bash
# Note: We use bash instead of sh because we need string replacement features!

# This build script was mostly generated by Gemini 3 Pro using my own build.sh script as reference

# ANSI Colors
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

# ---------------------------------------------------------
# Help Message Function
# ---------------------------------------------------------
show_help() {
    # generated by Gemini 3 Pro
    echo -e "${CYAN}Usage:${NC} ./scripts/play_match.sh [flags] [preset] [agent1] [agent2] [agent3]"
    echo ""
    echo -e "${YELLOW}Flags:${NC}"
    echo "  --seed <num>    Set a specific game seed (default: random)"
    echo "  --time <sec>    Set the server move time limit (default: 8)"
    echo "  --port <num>    Set the server port (default: 22135)"
    echo "  --no-server     Don't start any server"
    echo "  --help          Show this help message"
    echo ""
    echo -e "${YELLOW}Arguments (Cascading):${NC}"
    echo "  preset          CMake preset to use (e.g., gui-debug, headless-release)"
    echo "  agent1          The main agent (foreground, full output)"
    echo "  agent2          The second agent (background, hidden output)"
    echo "  agent3          The third agent (background, hidden output)"
    echo ""
    echo -e "${YELLOW}Cascading Logic:${NC}"
    echo "  - If agent2/agent3 are omitted, they copy the previous agent."
    echo "  - Example: './play_match.sh gui-debug smart' runs 3 smart agents."
    echo "  - Background agents are always forced to 'headless' mode."
    echo ""
    echo -e "${YELLOW}Examples:${NC}"
    echo "  ./scripts/play_match.sh                          # 3x Headless Randomizer bots"
    echo "  ./scripts/play_match.sh gui-debug human smart    # Human vs 2x Smart bots (GUI)"
    echo "  ./scripts/play_match.sh --seed 12345 smart       # 3x Smart bots with fixed seed"
    echo "  ./scripts/play_match.sh gui-debug human smart random # Mix of all three"
    exit 0
}

# ---------------------------------------------------------
# Flag Parsing
# ---------------------------------------------------------
# Default values
START_SERVER=1
HOST="127.0.0.1"
PORT="22135"
SEED=$((RANDOM * RANDOM))
TIME_LIMIT="8"

while [[ "$1" == --* ]] || [[ "$1" == "help" ]]; do
    case "$1" in
        --help|help) show_help ;;
        --seed) SEED="$2"; shift 2 ;;
        --time) TIME_LIMIT="$2"; shift 2 ;;
        --port) PORT="$2"; shift 2 ;;
        --no-server) START_SERVER=0; shift ;;
        *)
            echo -e "${RED}Unknown flag: $1${NC}"
            exit 1
            ;;
    esac
done

# ---------------------------------------------------------
# Argument Cascading Logic
# ---------------------------------------------------------
preset="${1:-headless-debug}"
if [ "$#" -gt 0 ]; then shift; fi

agent1="${1:-randomizer}"
if [ "$#" -gt 0 ]; then shift; fi

agent2="${1:-$agent1}"
if [ "$#" -gt 0 ]; then shift; fi

agent3="${1:-$agent2}"

# Derive Headless Preset
bg_preset="${preset/gui-/headless-}"
bg_preset="${bg_preset/tui-/headless-}"

# ---------------------------------------------------------
# Build Step
# ---------------------------------------------------------
echo -e "${CYAN}Building Main Preset: ${preset}...${NC}"
cmake --preset "$preset" > /dev/null
cmake --build --preset "$preset" > /dev/null

if [ "$preset" != "$bg_preset" ]; then
    echo -e "${CYAN}Building Background Preset: ${bg_preset}...${NC}"
    cmake --preset "$bg_preset" > /dev/null
    cmake --build --preset "$bg_preset" > /dev/null
fi

EXE_MAIN="./build/${preset}/agent-${agent1}"
EXE_BG2="./build/${bg_preset}/agent-${agent2}"
EXE_BG3="./build/${bg_preset}/agent-${agent3}"

# ---------------------------------------------------------
# Process Management
# ---------------------------------------------------------
trap 'echo -e "\n${RED}Shutting down server and background agents...${NC}"; kill $(jobs -p) 2>/dev/null || true' EXIT INT

echo "=========================================================="
echo -e " Launching Match"
echo -e "   Seed       : ${SEED}"
echo -e "   Time Limit : ${TIME_LIMIT}s"
if [[ ${START_SERVER} -gt 0 ]]; then
echo -e "   Server     : ${HOST}:${PORT}"
else
echo -e "   Server     : [Disabled]"
fi
echo -e "   Main       : ${YELLOW}$agent1${NC} ($preset) [Foreground]"
echo -e "   Bot 2      : ${YELLOW}$agent2${NC} ($bg_preset) [Hidden]"
echo -e "   Bot 3      : ${YELLOW}$agent3${NC} ($bg_preset) [Hidden]"
echo "=========================================================="

# 1. Boot the Java Server in the background
# UPDATED: Points to the new server/lib/native location!
if [[ ${START_SERVER} -gt 0 ]]; then
    java -Djava.library.path=./server/lib/native -Djava.awt.headless=true -jar ./server/ivoadk.jar headless quiet seed="$SEED" time="$TIME_LIMIT" > /dev/null 2>&1 &
    sleep 0.5
fi

# 2. Launch the hidden bots
"$EXE_BG2" "$HOST" "$PORT" "Bot2_${agent2}" > /dev/null 2>&1 &
sleep 0.1
"$EXE_BG3" "$HOST" "$PORT" "Bot3_${agent3}" > /dev/null 2>&1 &
sleep 0.1

# 3. Launch the active agent
time "$EXE_MAIN" "$HOST" "$PORT" "Player1_${agent1}"
