#!/bin/bash
# This script was generated by Gemini 3 Pro as well

# Note: No "set -e" here! We want to survive server crashes.

# ANSI Colors
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

# ---------------------------------------------------------
# Help Message Function
# ---------------------------------------------------------
show_help() {
    echo -e "${CYAN}Usage:${NC} ./scripts/run_server_loop.sh [flags]"
    echo ""
    echo -e "${YELLOW}Flags:${NC}"
    echo "  --port <num>    Run on port"
    echo "  --seed <num>    Set a specific game seed (omit for random)"
    echo "  --time <sec>    Set the server move time limit (default: 8)"
    echo "  --help          Show this help message"
    exit 0
}

# ---------------------------------------------------------
# Path Resolution
# ---------------------------------------------------------
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd "$SCRIPT_DIR/.." || exit 1

# ---------------------------------------------------------
# Default Variables
# ---------------------------------------------------------
TIME_LIMIT="8"
SEED="" # Empty by default so we know if the user provided one
PORT="22135"

# ---------------------------------------------------------
# Flag Parsing
# ---------------------------------------------------------
while [[ "$1" == --* ]] || [[ "$1" == "help" ]]; do
    case "$1" in
        --help|help) show_help ;;
        --seed) SEED="$2"; shift 2 ;;
        --time) TIME_LIMIT="$2"; shift 2 ;;
        --port) PORT="$2"; shift 2 ;;
        *)
            echo -e "${RED}Unknown flag: $1${NC}"
            exit 1
            ;;
    esac
done

# ---------------------------------------------------------
# Process Management (The Kill Switch)
# ---------------------------------------------------------
# When you hit Ctrl+C, it sends a SIGINT. We catch it and exit the script
# gracefully so the while loop breaks.
trap 'echo -e "\n${RED}Shutting down server loop...${NC}"; exit 0' INT

# ---------------------------------------------------------
# Command Builder
# ---------------------------------------------------------
# We use a bash array so we can safely append arguments without messing up quotes.
# Notice we removed the "quiet" flag so you get all the terminal output!
# TODO: pass seed to this function
CMD=(java -Djava.library.path=./server/lib/native -Djava.awt.headless=true -jar ./server/ivoadk.jar headless time="$TIME_LIMIT" port="$PORT")

# If the user provided a seed, append it to the command array
if [ -n "$SEED" ]; then
    CMD+=(seed="$SEED")
    SEED_DISPLAY="${SEED} (Fixed)"
else
    SEED_DISPLAY="Random (Delegated to Server)"
fi

echo -e "${GREEN}==========================================================${NC}"
echo -e " ${GREEN}Starting Continuous Server Loop${NC}"
echo -e "   Port       : ${PORT}"
echo -e "   Time Limit : ${TIME_LIMIT}s"
echo -e "   Seed       : ${SEED_DISPLAY}"
echo -e "   Stop       : Press ${YELLOW}Ctrl+C${NC} to exit"
echo -e "${GREEN}==========================================================${NC}"

# ---------------------------------------------------------
# The Infinite Loop
# ---------------------------------------------------------
while true; do
    echo -e "\n${CYAN}>>> Booting Server Instance...${NC}"

    # Run the server in the foreground.
    # The || true ensures the script doesn't panic if the Java server returns a crash code.
    "${CMD[@]}" || echo -e "${RED}>>> Server crashed or was forcefully terminated!${NC}"

    echo -e "${YELLOW}>>> Server stopped. Restarting in 1 second...${NC}"
    sleep 1
done
