name: Test MacOS (Clang)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        brew update
        brew install cmake ninja

    - name: Configure CMake
      run: cmake --preset headless-debug

    - name: Build
      run: cmake --build --preset headless-debug

    - name: Run tests
      run: ctest --preset headless-debug --output-on-failure
