#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <inttypes.h>

#include "minunit.h"
#include "utils/lcg.h"

int tests_run = 0;

static char error_msg[256];

#ifndef TEST_VECTOR_PATH
#define TEST_VECTOR_PATH "../../tests/fixtures/lcg_test_vectors.csv"
#endif

static char* test_lcg_with_csv_vectors(void) {
    // This test has been generated by Gemini 3 Pro because I coundn't be bothered to ._.
    FILE *file = fopen(TEST_VECTOR_PATH, "r");

    // Fallback if running directly from project root instead of build dir
    if (!file) {
        file = fopen("tests/fixtures/lcg_test_vectors.csv", "r");
    }

    if (!file) {
        return "Could not open lcg_test_vectors.csv. Did you run setup_fixtures.sh?";
    }

    lcg_t rng;
    char line[256];
    int line_num = 0;

    // Read the file line by line
    while (fgets(line, sizeof(line), file)) {
        line_num++;
        char op[32];
        long long expected;

        // Parse format: "operation, expected_value"
        if (sscanf(line, "%31[^,], %" SCNd64, op, &expected) == 2) {

            if (strcmp(op, "seed") == 0) {
                lcg_set_seed(&rng, (uint64_t)expected);
            }
            else if (strcmp(op, "int") == 0) {
                int32_t res = lcg_next_int(&rng);
                if (res != (int32_t)expected) {
                    snprintf(error_msg, sizeof(error_msg), "Line %d: Expected int %" PRId64 ", got %d", line_num, expected, res);
                    fclose(file);
                    return error_msg;
                }
            }
            else if (strncmp(op, "int-", 4) == 0) {
                // Extract the bound dynamically (e.g., "int-16" -> 16)
                int32_t bound = atoi(op + 4);
                int32_t res = lcg_next_int_n(&rng, bound);
                if (res != (int32_t)expected) {
                    snprintf(error_msg, sizeof(error_msg), "Line %d: Expected int-%d %" PRId64 ", got %d", line_num, bound, expected, res);
                    fclose(file);
                    return error_msg;
                }
            }
            else if (strcmp(op, "long") == 0) {
                int64_t res = lcg_next_long(&rng);
                if (res != (int64_t)expected) {
                    snprintf(error_msg, sizeof(error_msg), "Line %d: Expected long %" PRId64 ", got %" PRId64 "", line_num, expected, (int64_t)res);
                    fclose(file);
                    return error_msg;
                }
            }
            else {
                snprintf(error_msg, sizeof(error_msg), "Line %d: Unknown operation '%s'", line_num, op);
                fclose(file);
                return error_msg;
            }
        }
    }

    fclose(file);
    return 0; // 0 means success
}

static char* test_all(void) {
    printf("Running lcg tests...\n");
    mu_run_test(test_lcg_with_csv_vectors);
    return 0;
}

int main(void) {
    char *result = test_all();
    if (result != 0) {
        printf("FAILED: %s\n", result);
    }
    else {
        printf("ALL TESTS PASSED\n");
    }
    printf("Tests run: %d\n", tests_run);
    return result != 0;
}
